### ISSUE TITLE
Another typedesc issue, manifesting at runtime

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-serialization#5]
This is a followup on #4.

Last week the fix worked on my machine (I'm like 99% sure). This week it doesn't, I have a runtime exception when parsing.

This exception only happen when the type is passed as typedesc.

The branch is the same as before: https://github.com/status-im/nim-beacon-chain/tree/serialization_typedesc

- Commit: https://github.com/status-im/nim-beacon-chain/commit/1f4c4e8db2b334bb6d279bb5ac8f411535ef41a3

- Travis: https://travis-ci.org/status-im/nim-beacon-chain/jobs/533372351#L1268-L1271

And screenshots:

Working
![DeepinScreenshot_select-area_20190516165149](https://user-images.githubusercontent.com/22738317/57865438-e261c400-77fd-11e9-96e6-44ee1e037ac2.png)

Failing
![DeepinScreenshot_select-area_20190516165101](https://user-images.githubusercontent.com/22738317/57865504-fc030b80-77fd-11e9-9b95-118fad54e08b.png)

**Comment by mratsim** [comment]
The simple changes from

```Nim
proc parseTests*(jsonPath: string): ShufflingTests =
  result = Json.loadFile(jsonPath, ShufflingTests)
```

to

```Nim
proc parseTests*(jsonPath: string, T: typedesc = ShufflingTests): ShufflingTests =
  result = Json.loadFile(jsonPath, ShufflingTests)
```

will change the test from a pass to a stacktrace:

```
test_fixture_shuffling.nim(25) test_fixture_shuffling
serialization.nim(101)   parseTests
serialization.nim(46)    readValue
reader.nim(181)          readValue
object_serialization.nim(90) :anonymous
reader.nim(154)          readValue
reader.nim(181)          readValue
object_serialization.nim(90) :anonymous
reader.nim(171)          readValue
reader.nim(102)          skipToken
reader.nim(91)           requireToken
reader.nim(64)           raiseUnexpectedToken

    Unhandled exception:  [UnexpectedToken]
```

**Comment by zah** [comment]
This is the same issue, Mamy. 
I guess I should thank you for proving my point in https://github.com/nim-lang/Nim/issues/11225 that the underlying Nim issue is quite hard for the user to figure out.
